from app.ui.menu_schema import MenuI18n


MENU_ZH_TW: MenuI18n = {
    "control_center": "選單控制中心",
    "status_translation": "即時翻譯功能",
    "status_auto_detect": "自動偵測文字",
    "status_on": "啟用中",
    "status_off": "關閉中",
    "toggle_on": "開啟",
    "toggle_off": "關閉",
    "version": "當前版本 - V1.0.0 免費版",
    "quick_switch": "🌏 快速切換語言",
    "mode_prefix": "當前使用模式 - ",
    "mode_personal": "個人模式",
    "mode_group": "群組翻譯模式",
    "group_tip_personal": "把翻翻君加入群組後，可開啟群組多語翻譯。",
    "group_tip_group": "群組中可複選語言，之後每句都會固定翻譯。",
    "group_tip_bind": "尚未取得群組設定權限，請先輸入：綁定邀請者",
    "tutorial_title": "使用教學:",
    "tutorial_1": "1. 先用上方語言按鈕設定可翻譯語言",
    "tutorial_3": "3. 群組模式可複選語言並自動互譯",
    "tutorial_4": "4. 輸入 /menu 或 /選單 可隨時重開控制中心",
    "btn_help": "📘【教學中心】快速上手與完整教學",
    "btn_group_manage": "👥【群組翻譯】群組語言管理",
    "btn_group_intro": "👥【群組翻譯】群組功能說明",
    "btn_group_bind": "👥【群組翻譯】綁定邀請者",
    "btn_vip": "⭐【VIP 功能】Azure Translator｜高階翻譯能力",
    "auto_detect_target_name": "中文",
    "auto_detect_status_on": "開啟中",
    "auto_detect_status_off": "關閉中",
    "auto_detect_button_template": "🧠 {status} 自動偵測模式（非{target}訊息 -> {target}）",
    "tutorial_2_template": "2. 點擊自動偵測可啟用非{target} -> {target}翻譯",
}

