from app.ui.menu_schema import MenuI18n


MENU_EN: MenuI18n = {
    "control_center": "Control Center",
    "status_translation": "Realtime Translation",
    "status_auto_detect": "Auto Detect Text",
    "status_on": "ON",
    "status_off": "OFF",
    "toggle_on": "On",
    "toggle_off": "Off",
    "version": "Version - V1.0.0 Free",
    "quick_switch": "🌏 Quick Language Switch",
    "mode_prefix": "Current Mode - ",
    "mode_personal": "Personal",
    "mode_group": "Group Translation",
    "group_tip_personal": "Add FanFan to a group to enable multi-language translation.",
    "group_tip_group": "In groups, selected languages will be translated continuously.",
    "group_tip_bind": "No group permission yet, please bind inviter first.",
    "tutorial_title": "How to use:",
    "tutorial_1": "1. Set languages with the buttons above",
    "tutorial_3": "3. Group mode supports multi-language mutual translation",
    "tutorial_4": "4. Type /menu anytime to reopen control center",
    "btn_help": "📘 Help & Guide",
    "btn_group_manage": "👥 Group Language Settings",
    "btn_group_intro": "👥 Group Feature Guide",
    "btn_group_bind": "👥 Bind Group Inviter",
    "btn_vip": "⭐ VIP Feature | Azure Translator",
    "auto_detect_target_name": "English",
    "auto_detect_status_on": "ON",
    "auto_detect_status_off": "OFF",
    "auto_detect_button_template": "🧠 {status} Auto Detect Mode (Non-{target} -> {target})",
    "tutorial_2_template": "2. Enable auto detect for Non-{target} -> {target}",
}

