from app.ui.menu_schema import MenuI18n


MENU_MY: MenuI18n = {
    "control_center": "မီနူးထိန်းချုပ်ရေးစင်တာ",
    "status_translation": "အချိန်နှင့်တပြေးညီ ဘာသာပြန်",
    "status_auto_detect": "အလိုအလျောက်ရှာဖွေမှု",
    "status_on": "ဖွင့်ထားသည်",
    "status_off": "ပိတ်ထားသည်",
    "toggle_on": "ဖွင့်",
    "toggle_off": "ပိတ်",
    "version": "ဗားရှင်း - V1.0.0 အခမဲ့",
    "quick_switch": "🌏 ဘာသာစကား အမြန်ပြောင်း",
    "mode_prefix": "လက်ရှိမုဒ် - ",
    "mode_personal": "ကိုယ်ပိုင်မုဒ်",
    "mode_group": "အဖွဲ့ဘာသာပြန်မုဒ်",
    "group_tip_personal": "FanFan ကို group ထဲထည့်ပြီး ဘာသာစကားအများပြန်နိုင်သည်။",
    "group_tip_group": "Group ထဲတွင်ရွေးချယ်ထားသောဘာသာစကားများသို့ ဆက်တိုက်ဘာသာပြန်ပါမည်။",
    "group_tip_bind": "Group ခွင့်ပြုချက်မရှိသေးပါ၊ inviter ကို အရင်ချိတ်ပါ။",
    "tutorial_title": "အသုံးပြုပုံ:",
    "tutorial_1": "1. အပေါ်ဘက် button များဖြင့် ဘာသာစကားရွေးချယ်ပါ",
    "tutorial_3": "3. Group mode တွင် ဘာသာစကားအများ ပြန်နိုင်သည်",
    "tutorial_4": "4. /menu ဖြင့် control center ကို ပြန်ဖွင့်ပါ",
    "btn_help": "📘 လမ်းညွှန်",
    "btn_group_manage": "👥 Group ဘာသာစကားဆက်တင်",
    "btn_group_intro": "👥 Group လုပ်ဆောင်ချက်လမ်းညွှန်",
    "btn_group_bind": "👥 Group Inviter ချိတ်ရန်",
    "btn_vip": "⭐ VIP လုပ်ဆောင်ချက် | DeepL Pro",
    "auto_detect_target_name": "မြန်မာ",
    "auto_detect_status_on": "ဖွင့်ထားသည်",
    "auto_detect_status_off": "ပိတ်ထားသည်",
    "auto_detect_button_template": "🧠 {status} အလိုအလျောက်ရှာဖွေမှု ({target} မဟုတ် -> {target})",
    "tutorial_2_template": "2. Auto detect ဖြင့် {target} မဟုတ် -> {target} ပြောင်းပါ",
}

