from app.ui.menu_schema import MenuI18n


MENU_RU: MenuI18n = {
    "control_center": "Центр управления меню",
    "status_translation": "Мгновенный перевод",
    "status_auto_detect": "Автоопределение",
    "status_on": "Включено",
    "status_off": "Выключено",
    "toggle_on": "Вкл",
    "toggle_off": "Выкл",
    "version": "Версия - V1.0.0 Бесплатная",
    "quick_switch": "🌏 Быстрое переключение языка",
    "mode_prefix": "Текущий режим - ",
    "mode_personal": "Личный режим",
    "mode_group": "Групповой перевод",
    "group_tip_personal": "Добавьте FanFan в группу для многоязычного перевода.",
    "group_tip_group": "В группе сообщения переводятся на выбранные языки.",
    "group_tip_bind": "Нет прав группы, сначала привяжите пригласившего.",
    "tutorial_title": "Инструкция:",
    "tutorial_1": "1. Настройте язык кнопками выше",
    "tutorial_3": "3. В группе доступен взаимный перевод на несколько языков",
    "tutorial_4": "4. Введите /menu для повторного открытия центра",
    "btn_help": "📘 Руководство",
    "btn_group_manage": "👥 Настройки языка группы",
    "btn_group_intro": "👥 О функциях группы",
    "btn_group_bind": "👥 Привязать пригласившего",
    "btn_vip": "⭐ VIP Функция | DeepL Pro",
    "auto_detect_target_name": "Русский",
    "auto_detect_status_on": "ВКЛ",
    "auto_detect_status_off": "ВЫКЛ",
    "auto_detect_button_template": "🧠 {status} Автоопределение (не {target} -> {target})",
    "tutorial_2_template": "2. Включите автоопределение для не-{target} -> {target}",
}

