from app.ui.menu_schema import MenuI18n


MENU_JA: MenuI18n = {
    "control_center": "メニュー管理センター",
    "status_translation": "リアルタイム翻訳",
    "status_auto_detect": "自動言語検出",
    "status_on": "有効",
    "status_off": "無効",
    "toggle_on": "オン",
    "toggle_off": "オフ",
    "version": "バージョン - V1.0.0 無料版",
    "quick_switch": "🌏 言語クイック切替",
    "mode_prefix": "現在のモード - ",
    "mode_personal": "個人モード",
    "mode_group": "グループ翻訳モード",
    "group_tip_personal": "FanFanをグループに追加すると多言語翻訳が使えます。",
    "group_tip_group": "グループでは選択言語に継続翻訳します。",
    "group_tip_bind": "権限がありません。まず招待者を紐付けてください。",
    "tutorial_title": "使い方:",
    "tutorial_1": "1. 上のボタンで翻訳言語を設定",
    "tutorial_3": "3. グループで複数言語の相互翻訳",
    "tutorial_4": "4. /menu でいつでも再表示",
    "btn_help": "📘 使い方ガイド",
    "btn_group_manage": "👥 グループ言語設定",
    "btn_group_intro": "👥 グループ機能説明",
    "btn_group_bind": "👥 招待者を紐付け",
    "btn_vip": "⭐ VIP機能 | DeepL Pro",
    "auto_detect_target_name": "日本語",
    "auto_detect_status_on": "有効",
    "auto_detect_status_off": "無効",
    "auto_detect_button_template": "🧠 {status} 自動検出モード（非{target} -> {target}）",
    "tutorial_2_template": "2. 自動検出で非{target}を{target}へ翻訳",
}

